### ISSUE TITLE
HTTPS on http://jerichochat.tk/

### ISSUE THREAD

**Issue by SafwatHalaby** [joshua-m-david/jerichoencryption#1]
It is ironic that a software which is striving to be the most secure chat app in the world uses http on it main site.

**Comment by joshua-m-david** [comment]
I have moved hosting over to GitHub pages as it was getting too expensive to maintain a standalone server. It's accessible via HTTPS here: https://joshua-m-david.github.io/jerichoencryption/. Also it is possible to verify the authenticity of the content of the site as the site is stored in the gh-pages branch and tags (e.g. v1.5doc) are signed with my GPG key.

Key server 	x-hkp://pool.sks-keyservers.net
Key ID 	DC768471C467B6D0
Fingerprint 	CF3F 79EE 0114 59BA 0A59 9E9C DC76 8471 C467 B6D0
